version: "3"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5432"

  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      APP_KEYS: AKoNHCmXYLxkWnKYrVycOg==,fNyfrhOK9D3CWm78j9H9sQ==,k/SM5sN2VSZ8i5BMLRFuIw==,1wmaymLE5wD2ujl7JE6HTA==
      API_TOKEN_SALT: VbGkwJZuYhvqkI3AeqM7Vg==
      ADMIN_JWT_SECRET: inDLPLV9jQ2kCLq1qNg8Ug==
      JWT_SECRET: 5wsEyBrB5PjcYhYAJGJVLg==
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: false
    ports:
      - "1337"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      BASE_URL: http://strapi:1337
      UPLOADS_URL: http://localhost:80
    depends_on:
      - strapi
    ports:
      - "3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - strapi
    restart: always
    ports:
      - "80:80"
