version: '3'
services:
  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
      ADMIN_JWT_SECRET: 1a0507db15c17f359d9d8d47a73343d2
    volumes:
      - /srv/app/node_modules
      - ./backend:/srv/app/
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./backend/data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      BASE_URL: http://strapi:1337
      UPLOADS_URL: http://localhost:80
    depends_on:
      - strapi
    ports:
      - '3000'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'